### ISSUE TITLE
Не сохраняет состояние

### ISSUE THREAD

**Issue by neikila** [aluzgin/Android-Homework1#1]
1 открыть приложение
 2 добавить пару цифр
 3 свернуть приложение
 4 в терминале вызвать команду:
         adb shell am kill ru.mail.homework
         это сымитирует убийство системой приложения в фоне
5) открыть приложение из списка недавно запущенных
Ожидаемый результат: открыт список с добавленными цифрами
Фактический результат: открыт список без добавленных цифр

**Comment by aluzgin** [comment]
исправлено

**Comment by neikila** [comment]
Ок, исправлено
