### ISSUE TITLE
Не хватает интерфейса

### ISSUE THREAD

**Issue by neikila** [aluzgin/Android-Homework1#2]
https://github.com/aluzgin/Android-Homework1/blob/fa1a01f46d62454abce93e2c27cc56af799cee5d/app/src/main/java/ru/mail/homework/MainActivity.java#L21

Да, правильно, что этот метод реализован в Активити и через нее добавляется фрагмент, но в идеале нужно скрыть от адаптера и фрагменты и то в какой именно Активити они расположены, и оставить минимум необходимой им информации.

То есть вместо записи
`            ((MainActivity) context).fromFragmentData(number, color);`
должна быть запись
`            ((NumberViewer) context).fromFragmentData(number, color);`

где NumberViewer описан как:
`interface NumberViewer {
    void fromFragmentData(String number, int color)
}`
и имплементирован в активити

тогда адаптер знает только то, что он запущен внутри какой-то Активити, которая умеет показывать числа не более того.

**Comment by aluzgin** [comment]
исправлено

**Comment by neikila** [comment]
Принято
