### ISSUE TITLE
Вынос в константы

### ISSUE THREAD

**Issue by neikila** [aluzgin/Android-Homework1#3]
https://github.com/aluzgin/Android-Homework1/blob/fa1a01f46d62454abce93e2c27cc56af799cee5d/app/src/main/java/ru/mail/homework/MainActivity.java#L23

константы "number" и "color" выносят в константы:
`    public final static String COLOR_KEY = "color";`
и потом обращаются через переменную COLOR_KEY. В больших проектах эта практика позволяет значительно быстрее разобраться какие именно аргументы прилетают в какой фрагмент. Так как при помощи студии ты ищешь не полнотекстовый поиском, а ищешь использование конкретной переменной COLOR_KEY

причем если другому фрагменту потребуется передать цвет, то будет заведена другая константа.
таким образом исследовать код становится сильно проще.

Также если посмотришь примеры гугла или лекций, то увидишь, что код
`        Bundle bundle = new Bundle();
        bundle.putString("number", number);
        bundle.putInt("color", color);
`
выносят в статичный метод-конструктор **внутри** BigNumberFragment
в таком случае Активити даже не будет знать о том какие ключи используются фрагментом для хранения данных и какая структура у этих бандлов.
также это сильно упрощает создание этого фрагмента из других Активити (если бы они у тебя были)

**Comment by aluzgin** [comment]
исправлено

**Comment by neikila** [comment]
Да, все ок.
